### ISSUE TITLE
Questions for further development of user management

### ISSUE THREAD

**Issue by JessicaGuy** [fablabbcn/makeworks#39]
How can we manage "false" users created?
- currently, admins cannot delete fake user accounts, which give wrong data of total users of MW

**Comment by JessicaGuy** [comment]
As admin it is currently not possible to delete any user - a screenshot is attached
example user: https://make.works/admin/users/426

<img width="621" alt="Screenshot 2021-09-27 at 12 24 38" src="https://user-images.githubusercontent.com/44648706/134891801-0987181e-7c6a-405a-a7c1-5cdb88c94bda.png">

**Comment by viktorsmari** [comment]
@JessicaGuy that is because this user has been deleted, right?

Try this user that exists https://make.works/admin/users/420

**Comment by JessicaGuy** [comment]
@viktorsmari the error message comes up when I click "delete" as is the comand was not able to go through. I did the same with the user you have sent me, and the same message comes up.

**Comment by JessicaGuy** [comment]
This issue is still open.
In general, I believe we will have to "upgrade" the user management system, adding batch functions for example for deleting them and adding a captcha or similar to avoid more fake users.

Currently the workflow to delete "fake users" is:
1. Enter User page (front end) https://make.works/users/
2. Choose user to be deleted - opening in new tab
3. Add /admin/ in URL
4. Delete user in via admin page
This workflow exisits because this page https://make.works/admin/users is not available for me as an administrator to work on.

**Comment by benyscott** [comment]
I'd say for avoiding loads of fake account simply sending a confirmation email should do the trick?

Through the console I can find all the emails that has a weird ending, like somethingseomthing@something.in.net (see screenshot)

Although we wouldn't be doing it through the admin dashboard (for now) I could delete a good amount of spam emails (I think we can be confident that these .in.net emails are spam, they are super weird.

<img width="1117" alt="Screenshot 2023-01-24 at 18 18 54" src="https://user-images.githubusercontent.com/4509663/214370075-92d63079-e8bd-4b15-87f4-51fcf22af4c9.png">
