### ISSUE TITLE
deployment of this code into any gnu shell

### ISSUE THREAD

**Issue by ebosnic** [fablabbcn/makeworks#43]
Hello there... 
Ive tried to make this work on 4 different operating systems, still unsuccessful. 

Can you please specify a READ.me that explains what are dependencies in order to have this up and running ? pg for example does it need to have postgreesql installed and configured these databases you specified ? What about privileges to it ? 

I failed so far on Ubuntu, Fedora, Gentoo, and everything is fine with my setups, I can run any other rubyonrails app without this kind of issues. Also a lot of dependencies here are strictly versioned, in gem file or somewhere else. 

Is there any chance to get READ.me that explain how to set up this on for example some os of your choice, debian, fedora, ubuntu, rhel, even freebsd, or any other of your choice.

Thanks a bunch in advance.

**Comment by viktorsmari** [comment]
Are you able to create a new Rails app on your system?

By default rails uses sqlite but if you want to run this on Heroku you need to use postgresql.

Documenting how to install postgresql is out of the scope of this repository. I am able to clone and run this repository on 2 different machines, both running Ubuntu 20 and 21. They do have postgresql installed, and I followed some tutorial online (a while ago) on how to setup postgresql for my OS.

Where exactly are you having issues, which error message are you getting?

**Comment by ebosnic** [comment]
Dear Viktor, sir.. I'm doing this for 25+ years. professionally. Setting up and hosting various platforms. Did tons of ruby's, then ruby on rails, and so on. We can setup any dumy ruby on rails app in minutes. On any host you can imagine, localy, in a cloud, some dedicated vps, local vm, literately anything.. The thing is, when I try this one of yours, I'm having tons of issues with the database part, since in 
config/database.yml we have this 

[dbuser@fbc.maker.ba config]$ cat database.yml 
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: makeworks_dev

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] || 'makeworks_test' %>
  host: <%= ENV['TEST_DB_HOST'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>

production:
  <<: *default
  database: makeworks_prod
  
  
  I do not see here any database user with the privileges to create and destroy these db's you specified in this file.
  
  also, running this as simple user is not possible, user have to be sudo capable, once it's sudo capable, it asking for root and there is no root in db.
 
 so let me quote you, "by default rails uses sqlite" so that means I do not need any postgresql or any other datbase in order to run makerworks ? If database is needed, then, we have to configure database username password and database instance for it, and give it permissions so this user can do stuff with it. No ? 
 
 So please confirm that current config/database.yml file in this repo is just fine ? Why then it cant find a user when we try to run this :) I think we have to create the user and a database for it first.

**Comment by ebosnic** [comment]
and fur sure, here is the one example how database.yml should look like
for example if I do mysql behind it to run some dumy rails test.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: somedbusername       # MariaDB database user
  password: passwordofsomedbusername   # MariaDB user password
  host: localhost

this works like a charm for my dumy ruby on rails app.

**Comment by ebosnic** [comment]
thank you, will try like you described. Yes I can log in into psql as such user, no problems. After database issues are sorted out now take a look for example on http://18.157.85.174:3000/ it now says stuff like 

Application Trace | Framework Trace | Full Trace
app/views/application/_head.html.erb:31
app/views/layouts/blank.html.erb:4
app/controllers/welcome_controller.rb:18:in `index' 

and so on.

**Comment by viktorsmari** [comment]
The error you are getting is because you have not installed the javascript plugins yet.
To do that you need to run `yarn` OR `npm install`

https://guides.rubyonrails.org/getting_started.html

I would recommend against self hosting the application on a VPS.
I personally would rather use Heroku, it can cost as little as $7 per month (or $0) and save you a lot of time.

You can also see from here that you are in `development` mode. Remember to switch to `production` mode using the `RAILS_ENV` variable.
http://18.157.85.174:3000/version

**Comment by timcowlishaw** [comment]
Hi all, I'm closing this as it's been two years without any activity - I also added a more comprehensive 'development setup' section to the README a few months back which should help. For any further questions or improvements, please feel free to open a new ticket! Thanks.
