### ISSUE TITLE
admin "Users view" and mailgun

### ISSUE THREAD

**Issue by edskal** [fablabbcn/makeworks#45]
Hi Victor,

we are finalizing our work at maker.ba domain (content is not updated but thats easy).

I am having issue with admin/Users view (it. breaks looks like that it cannot pull list of users with GET. I see recent users and can edit each or by going to \:ID

second, mailgun test settings in production also dont work (two verifed emails are added to mailgun). Do you know what it could be.

Hosted on heroku. everything else works

**Comment by viktorsmari** [comment]
Yes, we had an issue with the `admin/users` view that we had not fixed at the time of releasing the project.
More details here where I was asking for help:
- https://stackoverflow.com/questions/68225398/using-ransackable-attributes-with-active-admin-errors
It was related to a conflict with the `activeadmin` gem and the `ransack` gem or a faulty configuration on our part.

We also have this endpoint to list users
- https://make.works/users

About the emails, here are the production settings:
https://github.com/fablabbcn/makeworks/blob/cc13afd4b57a7c20f2afc9f5e684a556d4644a31/config/environments/production.rb#L121-L126

Have you set both of these ENV vars (`MAILGUN_API_KEY`) in the Heroku web interface?

Next you need to find out _where_ the error is, on Heroku web interface, you can view the application log and see if it is trying to send emails.
You can also view logs on Mailgun and see if there is any activity there

**Comment by edskal** [comment]
Hmm interesting conflict of the rasak.

suggested users access is suitable.

we solved mailgun issue. No longer free for one custom domain :(.

thanx on support. I think we are technically ready, and now going after content only.
Many thanx
