### ISSUE TITLE
"randomize" Company page

### ISSUE THREAD

**Issue by JessicaGuy** [fablabbcn/makeworks#62]
Currently the Company/Manufacturer page always shows the same manufacturers on the same page. Hence, for people visiting the page the same 9 manufacturers have "priority". It would be nice to give everyone (Manufacturers & Regions) an equal opportunity for visibility. Currently the oldest listings are shown first (All from Make Works Scotland)

https://make.works/companies

**Comment by benyscott** [comment]
It's done, just need to push it to deploy, but maybe we could do it later when more changes are done. Talking to Victor on how to deploy to staging-makeworks first to check stuff.
