### ISSUE TITLE
Contributors can't edit

### ISSUE THREAD

**Issue by sallybourdon** [fablabbcn/makeworks#84]
After creating a listing, I am not able to edit or delete it

**Comment by JessicaGuy** [comment]
Have you filled in your profile with your name, foto and description? Most likely you are not asigned a region champion and therefor you cant see your created listings in your profile

**Comment by sallybourdon** [comment]
yes I have! It shows that I'm not assigned a region, but when I got to edit my user settings, there is no space to select a region. Also, now I see that I cannot add photos either... I'm guessing this is part of the same issue?
