### ISSUE TITLE
Access to repo / heroku / CSVs

### ISSUE THREAD

**Issue by timcowlishaw** [fablabbcn/makeworks#89]
Hey there @viktorsmari!

Hope you're well - @JessicaGuy  and @pral2a have asked me to take a look at a few issues on makeworks as well as smartcitizen over the next few months! I've managed to get a local development environment up and running with no problems, but there's a few other bits and pieces I need to get started, which I was wondering if you'd be able to help me with:

1) Contributor access to this repo
2) Access to the Heroku infrastructure for makeworks (staging and prod)
3) Copies of the seed data in `csv/` which isn't stored in git.

Would you be able to give me a hand with the above? I don't think i'll need anything else so shouldn't have to bother you again.

Thanks in advance!

Tim

**Comment by viktorsmari** [comment]
Hi @timcowlishaw - great to see someone working on this! I am happy to help and answer questions :nerd_face: 

I am one of **11 owners** of the `fablabbcn` organization that can give you access, @pral2a is one of them.
Did you talk to any of them already?

I think someone who currently works at `fablabbcn` should handle nr 1 and 2 - and I can help with the rest.

3. Do you need the CSV? Is it not enough to run `rails db:seed` ?

I think we only used the CSV approach to **migrate** from the Python flask app to Rails.

If you really need production data on your localhost, you should do a db dump from Heroku, but I think it's not needed :smile:

**Comment by timcowlishaw** [comment]
Hey Viktor!

Aha, apologies and thanks for the quick response. No need for the CSV's in that case, and I'll ask @pral2a about git write access and heroku directly :-)

**Comment by pral2a** [comment]
Access to Heroku granted :)

**Comment by timcowlishaw** [comment]
aha thank you @pral2a !
