### ISSUE TITLE
Country Selection / mobile version of the website 

### ISSUE THREAD

**Issue by MansiBavishiUAE** [fablabbcn/makeworks#92]
1. Currently only if i type Unite arab emirates does the country show up.  I should be able to type UAE and still the country should show up. 
2. After one fills the search selection, one needs to press search, it should auto populate 
3. Most of the users use the mobile version of the website, the mobile version needs to be more user friendly.

**Comment by timcowlishaw** [comment]
Thank you @MansiBavishiUAE! I have created new tickets for each of these so we can track them individually. The search-as-you-type improvement you suggested has just been released (2), so please do try it out and let us know what you think!
